# Name for the workflow
name: Deploy Frontend to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # --- FIX STARTS HERE ---

      - name: Install dependencies
        # Tell npm to run inside the /client directory
        working-directory: ./client
        run: npm ci
        
      - name: Build
        # Tell npm to run inside the /client directory
        working-directory: ./client
        run: npm run build
        
      # --- FIX ENDS HERE ---
        
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # --- NEW STEP REQUIRED ---
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload from the build output directory inside 'client'
          path: ./client/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        