# This workflow will build, test, and publish the 'server' package to the public npm registry.
# It is triggered automatically whenever a new release is created on GitHub.

name: Publish Server Package to npm

on:
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install server dependencies
        # The working-directory is crucial here. It tells npm to run
        # inside the /server folder.
        run: npm ci
        working-directory: ./server

      - name: Run server tests
        # This also runs inside the /server folder.
        # Make sure you have a "test" script in your server/package.json
        run: npm test
        working-directory: ./server

  publish-npm:
    # This job will only run if the build-and-test job succeeds
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # This configures .npmrc to authenticate with the public npm registry
          registry-url: 'https://registry.npmjs.org/'

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      - name: Publish to npm
        # This command also runs from within the /server directory
        run: npm publish
        working-directory: ./server
        env:
          # Your npm automation token is securely stored as a GitHub secret
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}